// File: db_aktifitas.js
// Data dari sheet Aktifitas Excel
const INIT_AKTIFITAS = [
  {
    "id": "ACT001",
    "visitId": "",
    "kontakToko": "[RTL068] Alkaff",
    "namaToko": "Toko Rehlah",
    "tanggalKunjungan": "2026-05-20",
    "orderKe": "Mustika Aroma",
    "jenisKunjungan": "Kunjungan Fisik",
    "aktifitas": "Observasi Pasar",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Logistik",
    "linkFoto": "https://drive.google.com/drive/folders/1LvoP23yYgafSg8UYRboX8neu0i_qCKl4?usp=drive_link",
    "keterangan": "Estimasi Orderan Terlalu Lama (33 Reve masih belum ready)",
    "status": "Active",
    "linkTersedia": "Melampirkan"
  },
  {
    "id": "ACT002",
    "visitId": "",
    "kontakToko": "[RTL070] Hifzi",
    "namaToko": "Bandung Parfum",
    "tanggalKunjungan": "2026-05-20",
    "orderKe": "Mustika Aroma",
    "jenisKunjungan": "Kunjungan Fisik",
    "aktifitas": "Observasi Pasar",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Layanan Agen",
    "linkFoto": "https://drive.google.com/drive/folders/1Ce9ZqeA3iVdqsPCNUr3G9QAMG45NMKxN?usp=drive_link",
    "keterangan": "Minim Knowledge",
    "status": "Active",
    "linkTersedia": "Melampirkan"
  },
  {
    "id": "ACT003",
    "visitId": "",
    "kontakToko": "[CRT00401] Susgiharti",
    "namaToko": "Aneka Parfume Luzi Indonesia",
    "tanggalKunjungan": "2026-05-20",
    "orderKe": "Kantor",
    "jenisKunjungan": "Kunjungan Fisik",
    "aktifitas": "Edukasi Produk",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Layanan Agen",
    "linkFoto": "https://drive.google.com/drive/folders/11PRlZ8jO9EG4nKa84PW3ELOV6xf6-rzQ?usp=drive_link",
    "keterangan": "Kurang Bayar Last Order Sekitar Rp. 172.100",
    "status": "Active",
    "linkTersedia": "Melampirkan"
  },
  {
    "id": "ACT004",
    "visitId": "",
    "kontakToko": "[RTL069] Hb. Husein Bin Syech Abubakar",
    "namaToko": "Toko Minyak Wangi Abu Iqbal",
    "tanggalKunjungan": "2026-05-20",
    "orderKe": "Mustika Aroma",
    "jenisKunjungan": "Kunjungan Fisik",
    "aktifitas": "Observasi Pasar",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "https://drive.google.com/drive/folders/1F62v1vP7iLU-Vk3T-rRhs5G9cbDek4J6?usp=drive_link",
    "keterangan": "Best Seller (Soft & Vanilla Bodies 182001)",
    "status": "Active",
    "linkTersedia": "Melampirkan"
  },
  {
    "id": "ACT005",
    "visitId": "",
    "kontakToko": "[RTL006] Saniya Nafisa",
    "namaToko": "Dialoq Parfume",
    "tanggalKunjungan": "2026-04-19",
    "orderKe": "Mustika Aroma",
    "jenisKunjungan": "Kunjungan Fisik",
    "aktifitas": "Penanganan Keluhan (Issue)",
    "kategoriSampling": "New Product",
    "sampleDescription": "10Ml Aroma Permintaan Sample Customer",
    "size": "10ml (10 Botol)",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Kasih 10 Aroma Variant yang diminta di Event ICI kemarin",
    "status": "Cold Lead",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT006",
    "visitId": "",
    "kontakToko": "[RTL006] Saniya Nafisa",
    "namaToko": "Dialoq Parfume",
    "tanggalKunjungan": "2026-05-20",
    "orderKe": "Kantor",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "All",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Logistik",
    "linkFoto": "",
    "keterangan": "Sebagian Orderan telah dikirim, ingin Estimasi yang belum (masih proses)",
    "status": "Cold Lead",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT007",
    "visitId": "",
    "kontakToko": "[CRT00408] M. Rifqi Fiqriansyah",
    "namaToko": "RF & Lylia Parfume",
    "tanggalKunjungan": "2026-05-21",
    "orderKe": "Kantor",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Penanganan Keluhan (Issue)",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "All",
    "linkFoto": "",
    "keterangan": "Folloq up, apakah ada kendala di orderan selama ini",
    "status": "Active",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT008",
    "visitId": "",
    "kontakToko": "[RTL071] Joji",
    "namaToko": "Jamalah Parfume",
    "tanggalKunjungan": "2026-05-20",
    "orderKe": "Mustika Aroma",
    "jenisKunjungan": "Kunjungan Fisik",
    "aktifitas": "Observasi Pasar",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "All",
    "linkFoto": "https://drive.google.com/drive/folders/1ulT04PCOf7rmE6nQgygtGvY6lFgovdML?usp=drive_link",
    "keterangan": "",
    "status": "Active",
    "linkTersedia": "Melampirkan"
  },
  {
    "id": "ACT009",
    "visitId": "",
    "kontakToko": "[RTL079] Naif Firdaus",
    "namaToko": "Ocean Perfume",
    "tanggalKunjungan": "2026-05-21",
    "orderKe": "",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Observasi Pasar",
    "kategoriSampling": "Sample Permintaan Customer",
    "sampleDescription": "Circle, Eso Tebe, Exclsuive Delline, Nine PM Reborn, Organize & Pink Button",
    "size": "3ml (6 Botol)",
    "keluhanFeedback": "",
    "linkFoto": "",
    "keterangan": "Permintaan Sample Customer 6 Aroma (Eso Tebe, Circle, Pink Button, Nine PM Reborn, Exclusive Delline & Organize)",
    "status": "",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT010",
    "visitId": "",
    "kontakToko": "[CRT00401] Susgiharti",
    "namaToko": "Aneka Parfume Luzi Indonesia",
    "tanggalKunjungan": "2026-05-22",
    "orderKe": "Kantor",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Follow Up Leads",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Follow up Kekurangan Pembayaran Last Nota Sebesar Rp. 173.000",
    "status": "Active",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT011",
    "visitId": "",
    "kontakToko": "[CRT00398] Khoironi",
    "namaToko": "Aliyah Parfume",
    "tanggalKunjungan": "2026-05-25",
    "orderKe": "Kantor",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Follow Up Leads",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Kirim Resi Orderan nya",
    "status": "Active",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT012",
    "visitId": "",
    "kontakToko": "[RTL073] Gojo",
    "namaToko": "PT Shanum Aditama Cosmind/PT SAG",
    "tanggalKunjungan": "2026-05-25",
    "orderKe": "Kantor",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Follow Up Leads",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "Nine PM Reborn, Gelato Pistachio & Organize",
    "size": "3ml (3 Botol)",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Follow up dari ICI2026 Kemarin",
    "status": "",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT013",
    "visitId": "",
    "kontakToko": "[RTL074] Hj. Darmawi",
    "namaToko": "Dylan Parfume",
    "tanggalKunjungan": "2026-05-25",
    "orderKe": "",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Follow Up Leads",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Menanyakan MOQ",
    "status": "Active",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT014",
    "visitId": "",
    "kontakToko": "[RTL095] Rifki Abdullah",
    "namaToko": "Robwah Parfume",
    "tanggalKunjungan": "2026-05-25",
    "orderKe": "Kantor",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Follow Up Leads",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Kirim Orderannya + Fragrance base 1Liter by Lalamove hari ini",
    "status": "",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT015",
    "visitId": "",
    "kontakToko": "[RTL081] Cahyadi",
    "namaToko": "Toko Wangi",
    "tanggalKunjungan": "2026-05-25",
    "orderKe": "",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Follow Up Leads",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Kirim Productlis Laverne April 2026",
    "status": "",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT016",
    "visitId": "",
    "kontakToko": "[RTL082] Vay",
    "namaToko": "PT Tribhakti Inspektama",
    "tanggalKunjungan": "2026-05-25",
    "orderKe": "",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Follow Up Leads",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Follow up dari ICI2026 Kemarin",
    "status": "",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT017",
    "visitId": "",
    "kontakToko": "[RTL080] Nico",
    "namaToko": "Mansion Parfume",
    "tanggalKunjungan": "2026-05-25",
    "orderKe": "",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Follow Up Leads",
    "kategoriSampling": "New Product",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Kirim Sample New Release Mei 2026",
    "status": "",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT018",
    "visitId": "",
    "kontakToko": "[RTL076] Ryan Nur Susanto",
    "namaToko": "Aroma Jiwa",
    "tanggalKunjungan": "2026-05-25",
    "orderKe": "",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Follow Up Leads",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Follow up dari ICI2026 Kemarin",
    "status": "",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT019",
    "visitId": "",
    "kontakToko": "[RTL078] Fahmi",
    "namaToko": "One Smith Perfume",
    "tanggalKunjungan": "2026-05-25",
    "orderKe": "",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Follow Up Leads",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Follow up dari ICI2026 Kemarin",
    "status": "",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT020",
    "visitId": "",
    "kontakToko": "[RTL075] Raden",
    "namaToko": "",
    "tanggalKunjungan": "2026-05-25",
    "orderKe": "",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Follow Up Leads",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Follow up dari ICI2026 Kemarin",
    "status": "",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT021",
    "visitId": "",
    "kontakToko": "[RTL077] Jendra P",
    "namaToko": "Alf Parfumery",
    "tanggalKunjungan": "2026-05-25",
    "orderKe": "",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Follow Up Leads",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Follow up dari ICI2026 Kemarin",
    "status": "",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT022",
    "visitId": "",
    "kontakToko": "[CRT00408] M. Rifqi Fiqriansyah",
    "namaToko": "RF & Lylia Parfume",
    "tanggalKunjungan": "2026-05-25",
    "orderKe": "Kantor",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Pengecekan Rutin/Maintenance",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Order Exclusive Delline 5kg*1 (Penurunan dikarenakan Bahan)",
    "status": "Active",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT023",
    "visitId": "",
    "kontakToko": "[RTL098] Nina",
    "namaToko": "",
    "tanggalKunjungan": "2026-05-25",
    "orderKe": "Mustika Aroma",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Monitoring Order",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Follow up Orderan ke Mustika Aroma (Ramping Jawa)",
    "status": "",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT024",
    "visitId": "",
    "kontakToko": "[RTL096] Ferdian",
    "namaToko": "",
    "tanggalKunjungan": "2026-05-25",
    "orderKe": "",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Follow up",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Follow up Rincian harga Sample Permintaan Customer",
    "status": "Prospect",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT025",
    "visitId": "",
    "kontakToko": "[RTL097] Arum Diah Pitaloka",
    "namaToko": "Arumi Parfume",
    "tanggalKunjungan": "2026-05-25",
    "orderKe": "Kantor",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Monitoring Order",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Order Roze Noire 5kg(fus) Langsung ke Kantor",
    "status": "Prospect",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT026",
    "visitId": "",
    "kontakToko": "[RTL099] I Nyoman Sukadana Wirya (Bayu)",
    "namaToko": "Dupa Harum Maha Dewa",
    "tanggalKunjungan": "2026-05-25",
    "orderKe": "",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Follow Up Leads",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Follow up kembali Leads dari Admin NW",
    "status": "Prospect",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT027",
    "visitId": "",
    "kontakToko": "[RTL101] Abu",
    "namaToko": "",
    "tanggalKunjungan": "2026-05-25",
    "orderKe": "",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Edukasi Produk",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Follow up ada Variant Baru di agen resmi",
    "status": "",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT028",
    "visitId": "",
    "kontakToko": "[RTL100] David",
    "namaToko": "Arometry Perfume",
    "tanggalKunjungan": "2026-05-25",
    "orderKe": "",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Edukasi Produk",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Follow up Rincian harga Sample Permintaan Customer",
    "status": "Prospect",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT029",
    "visitId": "",
    "kontakToko": "[CRT00400] Abdul Kholil",
    "namaToko": "Toko Hafizh",
    "tanggalKunjungan": "2026-05-25",
    "orderKe": "",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Monitoring Order",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Follow up Besok ke Store untuk kirim sample terbaru Laverne",
    "status": "Active",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT030",
    "visitId": "",
    "kontakToko": "[RTL098] Nina",
    "namaToko": "",
    "tanggalKunjungan": "2026-05-26",
    "orderKe": "",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Edukasi Produk",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Edukasi Brand Lain Selain Labor & Laverne yang ada di Nilam Widuri",
    "status": "",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT031",
    "visitId": "",
    "kontakToko": "[RTL079] Naif Firdaus",
    "namaToko": "Ocean Perfume",
    "tanggalKunjungan": "2026-05-28",
    "orderKe": "",
    "jenisKunjungan": "Kunjungan Fisik",
    "aktifitas": "Edukasi Produk",
    "kategoriSampling": "New Product",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Kirim Sample New Release Mei 2026",
    "status": "",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT032",
    "visitId": "",
    "kontakToko": "[CRT00400] Abdul Kholil",
    "namaToko": "Toko Hafizh",
    "tanggalKunjungan": "2026-05-28",
    "orderKe": "",
    "jenisKunjungan": "Kunjungan Fisik",
    "aktifitas": "Edukasi Produk",
    "kategoriSampling": "New Product",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Kirim Sample New Release Mei 2026",
    "status": "Active",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT033",
    "visitId": "",
    "kontakToko": "[CRT00369] Faiz Rafi Darmanto",
    "namaToko": "Allumere Parfume",
    "tanggalKunjungan": "2026-05-26",
    "orderKe": "Kantor",
    "jenisKunjungan": "Kunjungan Fisik",
    "aktifitas": "Edukasi Produk",
    "kategoriSampling": "New Product",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Kirim Sample New Release Mei 2026",
    "status": "Active",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT034",
    "visitId": "",
    "kontakToko": "[CRT00401] Susgiharti",
    "namaToko": "Aneka Parfume Luzi Indonesia",
    "tanggalKunjungan": "2026-05-25",
    "orderKe": "Kantor",
    "jenisKunjungan": "Kunjungan Fisik",
    "aktifitas": "Edukasi Produk",
    "kategoriSampling": "New Product",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Kirim Sample New Release Mei 2026",
    "status": "Active",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT035",
    "visitId": "",
    "kontakToko": "[RTL102] Fadli",
    "namaToko": "Johar Perfume",
    "tanggalKunjungan": "2026-05-26",
    "orderKe": "",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Edukasi Produk",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Edukasi New Release Variant Baru Laverne",
    "status": "Prospect",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT036",
    "visitId": "",
    "kontakToko": "[RTL103] Gunawan",
    "namaToko": "",
    "tanggalKunjungan": "2026-05-26",
    "orderKe": "",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Edukasi Produk",
    "kategoriSampling": "Sample Permintaan Customer",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Menunggu Alamat Penerima dari Customer",
    "status": "Prospect",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT037",
    "visitId": "",
    "kontakToko": "[RTL058] Sharron",
    "namaToko": "Syrent Scent",
    "tanggalKunjungan": "2026-05-26",
    "orderKe": "",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Edukasi Produk",
    "kategoriSampling": "New Product",
    "sampleDescription": "Bloom Into Essence Series",
    "size": "3ml (10 Botol)",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Packing Sample untuk dikirim hari ini Mengunakan MAS Cargo",
    "status": "",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT038",
    "visitId": "",
    "kontakToko": "[CRT00378] Arif Firman",
    "namaToko": "Mustika Parfume",
    "tanggalKunjungan": "2026-05-25",
    "orderKe": "Kantor",
    "jenisKunjungan": "Kunjungan Fisik",
    "aktifitas": "Observasi Pasar",
    "kategoriSampling": "New Product",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Kirim Sample New Release Laverne Bulan Mei 2026",
    "status": "Active",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT039",
    "visitId": "",
    "kontakToko": "[RTL100] David",
    "namaToko": "Arometry Perfume",
    "tanggalKunjungan": "2026-05-26",
    "orderKe": "",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Edukasi Produk",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Menanyakan Notes Guidance Amouvelle",
    "status": "Prospect",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT040",
    "visitId": "",
    "kontakToko": "[RTL104] Murtadho Alkaff",
    "namaToko": "Karisma Parfume",
    "tanggalKunjungan": "2026-05-21",
    "orderKe": "Mustika Aroma",
    "jenisKunjungan": "Kunjungan Fisik",
    "aktifitas": "Observasi Pasar",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Checking Aroma Hype Tahun ini",
    "status": "Active",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT041",
    "visitId": "",
    "kontakToko": "[RTL105] Syarif Muhammad",
    "namaToko": "Jadid Parfume",
    "tanggalKunjungan": "2026-05-21",
    "orderKe": "Mustika Aroma",
    "jenisKunjungan": "Kunjungan Fisik",
    "aktifitas": "Observasi Pasar",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Checking Aroma Hype Tahun ini",
    "status": "Active",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT042",
    "visitId": "",
    "kontakToko": "[RTL106] Yusuf",
    "namaToko": "Nine Parfume",
    "tanggalKunjungan": "2026-05-21",
    "orderKe": "",
    "jenisKunjungan": "Kunjungan Fisik",
    "aktifitas": "Observasi Pasar",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Checking Aroma Hype Tahun ini",
    "status": "",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT043",
    "visitId": "",
    "kontakToko": "[RTL060] Nurul Aulia Dewi",
    "namaToko": "Bestie Parfum Belopa",
    "tanggalKunjungan": "2026-05-26",
    "orderKe": "",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Edukasi Produk",
    "kategoriSampling": "Sample Permintaan Customer",
    "sampleDescription": "15 Sample Best Seller Laverne",
    "size": "3ml (15 Botol)",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Kirim + Packing Sample Permintaan Best Seller Customer",
    "status": "",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT044",
    "visitId": "",
    "kontakToko": "[RTL100] David",
    "namaToko": "Arometry Perfume",
    "tanggalKunjungan": "2026-05-28",
    "orderKe": "",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Permintaan Sample Customer",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Membuat Rincian Harga",
    "status": "Prospect",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT045",
    "visitId": "",
    "kontakToko": "[RTL058] Sharron",
    "namaToko": "Syrent Scent",
    "tanggalKunjungan": "2026-05-28",
    "orderKe": "",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Edukasi Produk",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Order Vanilla Six ke Agen",
    "status": "",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT046",
    "visitId": "",
    "kontakToko": "[RTL107] Ilham",
    "namaToko": "Ocean Fragrance",
    "tanggalKunjungan": "2026-05-28",
    "orderKe": "",
    "jenisKunjungan": "Kunjungan Fisik",
    "aktifitas": "Edukasi Produk",
    "kategoriSampling": "New Product",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Kirim Sample New Release Laverne Bulan Mei 2026",
    "status": "",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT047",
    "visitId": "",
    "kontakToko": "[RTL108] Wawan",
    "namaToko": "Toko Mubarok Parfume",
    "tanggalKunjungan": "2026-05-21",
    "orderKe": "Mustika Aroma",
    "jenisKunjungan": "Kunjungan Fisik",
    "aktifitas": "Observasi Pasar",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Checking Aroma Laverne yang lagi Hype (33 Reve & 31 Reve)",
    "status": "Active",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT048",
    "visitId": "",
    "kontakToko": "[RTL073] Gojo",
    "namaToko": "PT Shanum Aditama Cosmind/PT SAG",
    "tanggalKunjungan": "2026-06-02",
    "orderKe": "Kantor",
    "jenisKunjungan": "Event ICI",
    "aktifitas": "Follow up",
    "kategoriSampling": "Sample Permintaan Customer",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Follow up Kembali Lead ICI2026",
    "status": "",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT049",
    "visitId": "",
    "kontakToko": "[RTL082] Vay",
    "namaToko": "PT Tribhakti Inspektama",
    "tanggalKunjungan": "2026-06-02",
    "orderKe": "",
    "jenisKunjungan": "Event ICI",
    "aktifitas": "Follow Up Leads",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Follow up Kembali Lead ICI2026",
    "status": "",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT050",
    "visitId": "",
    "kontakToko": "[RTL076] Ryan Nur Susanto",
    "namaToko": "Aroma Jiwa",
    "tanggalKunjungan": "2026-06-02",
    "orderKe": "",
    "jenisKunjungan": "Event ICI",
    "aktifitas": "Follow Up Leads",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Follow up Kembali Lead ICI2026",
    "status": "",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT051",
    "visitId": "",
    "kontakToko": "[RTL078] Fahmi",
    "namaToko": "One Smith Perfume",
    "tanggalKunjungan": "2026-06-02",
    "orderKe": "",
    "jenisKunjungan": "Event ICI",
    "aktifitas": "Follow Up Leads",
    "kategoriSampling": "Sample Permintaan Customer",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Packing Sample untuk dikirim hari ini Mengunakan MAS Cargo",
    "status": "",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT052",
    "visitId": "",
    "kontakToko": "[RTL100] David",
    "namaToko": "Arometry Perfume",
    "tanggalKunjungan": "2026-05-29",
    "orderKe": "",
    "jenisKunjungan": "Event ICI",
    "aktifitas": "Follow Up Leads",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Menanyakan Pricelist 100gr Aroma yang dibutuhkan",
    "status": "Prospect",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT053",
    "visitId": "",
    "kontakToko": "[RTL110] Deni Hariyanto",
    "namaToko": "Rizky Parfume",
    "tanggalKunjungan": "2026-06-02",
    "orderKe": "Kantor",
    "jenisKunjungan": "Event ICI",
    "aktifitas": "Edukasi Produk",
    "kategoriSampling": "Sample Permintaan Customer",
    "sampleDescription": "Tamburins All Sreies",
    "size": "3ml (4 Botol)",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Packing Sample untuk dikirim hari ini Mengunakan MAS Cargo",
    "status": "Active",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT054",
    "visitId": "",
    "kontakToko": "[RTL100] David",
    "namaToko": "Arometry Perfume",
    "tanggalKunjungan": "2026-06-02",
    "orderKe": "",
    "jenisKunjungan": "Event ICI",
    "aktifitas": "Edukasi Produk",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Price Nine PM Reborn 100gr",
    "status": "Prospect",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT055",
    "visitId": "",
    "kontakToko": "[RTL111] Asep",
    "namaToko": "Toko Scentoria Fragrance Compounds",
    "tanggalKunjungan": "2026-06-02",
    "orderKe": "",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Follow Up Leads",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Follow up Leads dari Admin NW",
    "status": "",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT056",
    "visitId": "",
    "kontakToko": "[RTL058] Sharron",
    "namaToko": "Syrent Scent",
    "tanggalKunjungan": "2026-06-02",
    "orderKe": "Kantor",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Follow up",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Follow up Orderan yang Ready tuk dikirim by Paxel dari Pabrik",
    "status": "",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT057",
    "visitId": "",
    "kontakToko": "[RTL098] Nina",
    "namaToko": "",
    "tanggalKunjungan": "2026-05-26",
    "orderKe": "",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Follow up",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Mencari Aroma (Jaguar Blue) dan Brand apa aja yang ada di PT Nilam Widuri",
    "status": "",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT058",
    "visitId": "",
    "kontakToko": "[RTL103] Gunawan",
    "namaToko": "",
    "tanggalKunjungan": "2026-06-02",
    "orderKe": "",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Follow up",
    "kategoriSampling": "Sample Permintaan Customer",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Follow up Leads karena masih not responded minggu kemarin",
    "status": "Prospect",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT059",
    "visitId": "",
    "kontakToko": "[RTL089] Satrio Winandi",
    "namaToko": "Paragon Fragrance",
    "tanggalKunjungan": "",
    "orderKe": "Mustika Aroma",
    "jenisKunjungan": "Kunjungan Fisik",
    "aktifitas": "Edukasi Produk",
    "kategoriSampling": "New Product",
    "sampleDescription": "Bloom Into Essence Series",
    "size": "3ml (10 Botol)",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Kirim Sample + Orderan Agen ke Customer",
    "status": "Active",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT060",
    "visitId": "",
    "kontakToko": "[RTL112] Nurkholis Majid",
    "namaToko": "Al Majid Parfum",
    "tanggalKunjungan": "2026-06-02",
    "orderKe": "",
    "jenisKunjungan": "Remote Coverage (Call/WA)",
    "aktifitas": "Follow Up Leads",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Kirim Productlis Laverne Mei 2026",
    "status": "",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT061",
    "visitId": "",
    "kontakToko": "[RTL075] Raden",
    "namaToko": "",
    "tanggalKunjungan": "2026-06-02",
    "orderKe": "",
    "jenisKunjungan": "Event ICI",
    "aktifitas": "Follow Up Leads",
    "kategoriSampling": "Tidak sampling (Fokus Edukasi)",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Follow up Kembali Lead ICI2026",
    "status": "",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT062",
    "visitId": "",
    "kontakToko": "[RTL095] Rifki Abdullah",
    "namaToko": "Robwah Parfume",
    "tanggalKunjungan": "2026-06-02",
    "orderKe": "Kantor",
    "jenisKunjungan": "Event ICI",
    "aktifitas": "Follow up",
    "kategoriSampling": "New Product",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "Tidak ada keluhan",
    "linkFoto": "",
    "keterangan": "Follow up Sample New Release, apakah sudah Menerima",
    "status": "",
    "linkTersedia": "Tidak Melampirkan"
  },
  {
    "id": "ACT063",
    "visitId": "",
    "kontakToko": "[RTL 117] Michael",
    "namaToko": "AROMATIKA",
    "tanggalKunjungan": "2026-06-10",
    "orderKe": "Mustika Aroma",
    "jenisKunjungan": "Kunjungan Fisik",
    "aktifitas": "",
    "kategoriSampling": "",
    "sampleDescription": "",
    "size": "",
    "keluhanFeedback": "",
    "linkFoto": "",
    "keterangan": "",
    "status": "Active",
    "linkTersedia": "Tidak Melampirkan"
  }
];
