// File: db_plan.js
// Data dari sheet Visit Plan Excel
const INIT_PLAN = [
  {
    "id": "VP001",
    "kontakToko": "[RTL068] Alkaff",
    "namaToko": "Toko Rehlah",
    "tujuanKunjungan": "Observasi Pasar",
    "pic": "Ali",
    "planDate": "2026-05-20",
    "actualDate": "2026-05-20",
    "priority": "High",
    "status": "Visited",
    "keterangan": "Mencari Data Kompetitor",
    "daysUntilDue": "Done"
  },
  {
    "id": "VP002",
    "kontakToko": "[RTL070] Hifzi",
    "namaToko": "Bandung Parfum",
    "tujuanKunjungan": "Observasi Pasar",
    "pic": "Ali",
    "planDate": "2026-05-20",
    "actualDate": "2026-05-20",
    "priority": "Low",
    "status": "Visited",
    "keterangan": "Checking Pengambilan Variant ke Agen",
    "daysUntilDue": "Done"
  },
  {
    "id": "VP003",
    "kontakToko": "[RTL069] Hb. Husein Bin Syech Abubakar",
    "namaToko": "Toko Minyak Wangi Abu Iqbal",
    "tujuanKunjungan": "Observasi Pasar",
    "pic": "Ali",
    "planDate": "2026-05-20",
    "actualDate": "2026-05-20",
    "priority": "Medium",
    "status": "Visited",
    "keterangan": "Checking Aroma Hype Tahun ini",
    "daysUntilDue": "Done"
  },
  {
    "id": "VP004",
    "kontakToko": "[CRT00401] Susgiharti",
    "namaToko": "Aneka Parfume Luzi Indonesia",
    "tujuanKunjungan": "Observasi Pasar",
    "pic": "Ali",
    "planDate": "2026-05-20",
    "actualDate": "2026-05-20",
    "priority": "High",
    "status": "Visited",
    "keterangan": "Mencari Data Kompetitor",
    "daysUntilDue": "Done"
  },
  {
    "id": "VP005",
    "kontakToko": "[RTL071] Joji",
    "namaToko": "Jamalah Parfume",
    "tujuanKunjungan": "Observasi Pasar",
    "pic": "Ali",
    "planDate": "2026-05-20",
    "actualDate": "2026-05-20",
    "priority": "Low",
    "status": "Visited",
    "keterangan": "Checking Aroma Hype Tahun ini",
    "daysUntilDue": "Done"
  },
  {
    "id": "VP006",
    "kontakToko": "[RTL104] Murtadho Alkaff",
    "namaToko": "Karisma Parfume",
    "tujuanKunjungan": "Observasi Pasar",
    "pic": "Ali",
    "planDate": "2026-05-21",
    "actualDate": "2026-05-21",
    "priority": "Medium",
    "status": "Visited",
    "keterangan": "Badboy CH from TFI lagi Hype Tahun ini",
    "daysUntilDue": "Done"
  },
  {
    "id": "VP007",
    "kontakToko": "[RTL105] Syarif Muhammad",
    "namaToko": "Jadid Parfume",
    "tujuanKunjungan": "Observasi Pasar",
    "pic": "Ali",
    "planDate": "2026-05-21",
    "actualDate": "2026-05-21",
    "priority": "Medium",
    "status": "Visited",
    "keterangan": "31 Reve from Laverne lagi hype di area Condet (2.000/ml)",
    "daysUntilDue": "Done"
  },
  {
    "id": "VP008",
    "kontakToko": "[RTL106] Yusuf",
    "namaToko": "Nine Parfume",
    "tujuanKunjungan": "Observasi Pasar",
    "pic": "Ali",
    "planDate": "2026-05-21",
    "actualDate": "2026-05-21",
    "priority": "Low",
    "status": "Visited",
    "keterangan": "33 Reve & Nine PM Reborn lagi Hype dan Stok Menipis (1.500/ml)",
    "daysUntilDue": "Done"
  },
  {
    "id": "VP009",
    "kontakToko": "[CRT00401] Susgiharti",
    "namaToko": "Aneka Parfume Luzi Indonesia",
    "tujuanKunjungan": "Edukasi Produk",
    "pic": "Ali",
    "planDate": "2026-05-25",
    "actualDate": "2026-05-20",
    "priority": "High",
    "status": "Visited",
    "keterangan": "Kasih Sampling Aroma Baru Laverne",
    "daysUntilDue": "Done"
  },
  {
    "id": "VP010",
    "kontakToko": "[RTL066] Ica Yunita",
    "namaToko": "True Love Scent",
    "tujuanKunjungan": "Edukasi Produk",
    "pic": "Ali",
    "planDate": "2026-06-05",
    "actualDate": "",
    "priority": "Medium",
    "status": "Scheduled",
    "keterangan": "Kirim Sample 3 Variant Permintaan Customer (Jasmine Angle, Nine PM Reborn & Cherries Electra)",
    "daysUntilDue": "1"
  },
  {
    "id": "VP011",
    "kontakToko": "[RTL065] Prabu",
    "namaToko": "Ar Rayan Parfume",
    "tujuanKunjungan": "Edukasi Produk",
    "pic": "Ali",
    "planDate": "2026-06-05",
    "actualDate": "",
    "priority": "Medium",
    "status": "Scheduled",
    "keterangan": "Kirim Sample 4 Variant Permintaan Customer (Plutonium, Scan Secret, Nine PM Reborn & Node Zara)",
    "daysUntilDue": "1"
  },
  {
    "id": "VP012",
    "kontakToko": "[RTL031] Johan",
    "namaToko": "Info Parfume",
    "tujuanKunjungan": "Edukasi Produk",
    "pic": "Ali",
    "planDate": "2026-06-05",
    "actualDate": "",
    "priority": "Medium",
    "status": "Scheduled",
    "keterangan": "Kirim Sample 5 Variant Permintaan Customer (Desert, Scan Secret, Soulmate, Boost Emotion & Blue Chance)",
    "daysUntilDue": "1"
  },
  {
    "id": "VP013",
    "kontakToko": "[RTL070] Hifzi",
    "namaToko": "Bandung Parfum",
    "tujuanKunjungan": "Observasi Pasar",
    "pic": "Ali",
    "planDate": "2026-05-20",
    "actualDate": "2026-05-20",
    "priority": "Low",
    "status": "Visited",
    "keterangan": "Mencari Data Kompetitor",
    "daysUntilDue": "Done"
  },
  {
    "id": "VP014",
    "kontakToko": "[RTL107] Ilham",
    "namaToko": "Ocean Fragrance",
    "tujuanKunjungan": "Edukasi Produk",
    "pic": "Ali",
    "planDate": "2026-05-28",
    "actualDate": "2026-05-28",
    "priority": "Low",
    "status": "Visited",
    "keterangan": "Kirim Sample Laverne 2026",
    "daysUntilDue": "Done"
  },
  {
    "id": "VP015",
    "kontakToko": "[CRT00400] Abdul Kholil",
    "namaToko": "Toko Hafizh",
    "tujuanKunjungan": "Edukasi Produk",
    "pic": "Ali",
    "planDate": "2026-05-26",
    "actualDate": "2026-05-25",
    "priority": "Medium",
    "status": "Visited",
    "keterangan": "Kirim Sample Laverne 2026",
    "daysUntilDue": "Done"
  },
  {
    "id": "VP016",
    "kontakToko": "[RTL079] Naif Firdaus",
    "namaToko": "Ocean Perfume",
    "tujuanKunjungan": "Edukasi Produk",
    "pic": "Ali",
    "planDate": "2026-05-26",
    "actualDate": "2026-05-21",
    "priority": "Medium",
    "status": "Visited",
    "keterangan": "Kirim Sample Laverne 2026",
    "daysUntilDue": "Done"
  },
  {
    "id": "VP017",
    "kontakToko": "[CRT00369] Faiz Rafi Darmanto",
    "namaToko": "Allumere Parfume",
    "tujuanKunjungan": "Edukasi Produk",
    "pic": "Ali",
    "planDate": "2026-05-26",
    "actualDate": "2026-05-26",
    "priority": "High",
    "status": "Visited",
    "keterangan": "Kirim Sample Laverne 2026",
    "daysUntilDue": "Done"
  },
  {
    "id": "VP018",
    "kontakToko": "[RTL108] Wawan",
    "namaToko": "Toko Mubarok Parfume",
    "tujuanKunjungan": "Observasi Pasar",
    "pic": "Ali",
    "planDate": "2026-05-21",
    "actualDate": "2026-05-21",
    "priority": "Medium",
    "status": "Visited",
    "keterangan": "Checking Aroma Hype Tahun ini",
    "daysUntilDue": "Done"
  },
  {
    "id": "VP019",
    "kontakToko": "[RTL089] Satrio Winandi",
    "namaToko": "Paragon Fragrance",
    "tujuanKunjungan": "Edukasi Produk",
    "pic": "Ali",
    "planDate": "2026-06-02",
    "actualDate": "",
    "priority": "Medium",
    "status": "Overdue",
    "keterangan": "Mencari Data Kompetitor",
    "daysUntilDue": "-2"
  },
  {
    "id": "VP020",
    "kontakToko": "[RTL 117] Michael",
    "namaToko": "AROMATIKA",
    "tujuanKunjungan": "Pengecekan Rutin/Maintenance",
    "pic": "Thia",
    "planDate": "2026-06-03",
    "actualDate": "2026-06-10",
    "priority": "Low",
    "status": "Visited",
    "keterangan": "",
    "daysUntilDue": "Done"
  }
];
